server:
  port: 8088

app:
  jwtSecret: c717ae5065c1b297def63ab78cc5e3bbaaa7aba445d91ff31c8ea025ef214633
  jwtExpirationMs: 3600000

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/fake_store_db
    driverClassName: org.postgresql.Driver
    username: postgres
    password: password
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  cloud:
    compatibility-verifier:
      enabled: false