app:
  jwtSecret: YourSecretKeyHere
  jwtExpirationMs: 3600000

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/fake_store_db
    driverClassName: org.postgresql.Driver
    username: postgres
    password: password
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8085

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html